augmentation: true
aux_loss: false
base_chan: 32
batch_size: 12
block_list: '1234'
crop: false
early_stopping: 50
epochs: 80
lr: 0.0001
momentum: 0.9
name: AttentionUNet
nesterov: false
num_blocks:
- 1
- 1
- 1
- 1
num_class: 1
num_workers: 14
optimizer: Adam
reduce_size: 8
weight_decay: 0.0001
